name: Deploy React Projects

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Todo App
      - name: Install Todo App dependencies
        working-directory: Todo-App
        run: npm ci

      - name: Build Todo App
        working-directory: Todo-App
        run: npm run build

      # Calculator
      - name: Install Calculator dependencies
        working-directory: Calculator
        run: npm ci

      - name: Build Calculator
        working-directory: Calculator
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare Pages artifact
        run: |
          mkdir -p pages/Todo-App
          mkdir -p pages/Calculator

          cp -r Todo-App/dist/* pages/Todo-App/
          cp -r Calculator/dist/* pages/Calculator/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
